-- Insert Data into Systems Table
INSERT INTO main_part_category (main_part_category_name)
VALUES ('Exterior Parts'),
       ('Interior Parts'),
       ('Engine and Related Components'),
       ('Transmission System'),
       ('Suspension and Steering'),
       ('Brake System'),
       ('Exhaust System'),
       ('Electrical System'),
       ('Fuel System'),
       ('Miscellaneous');

INSERT INTO `country`
VALUES (1, 'BR', 'Brazil'),
       (2, 'CA', 'Canada'),
       (3, 'DE', 'Germany'),
       (4, 'IN', 'India'),
       (5, 'GR', 'Greece'),
       (6, 'US', 'United States');

INSERT INTO `state`
VALUES (1, 'Attica / Αττική', 5),
       (2, 'Central Greece / Στερεά Ελλάδα', 5),
       (3, 'Central Macedonia / Κεντρική Μακεδονία', 5),
       (4, 'Crete / Κρήτη', 5),
       (5, 'Eastern Macedonia and Thrace / Ανατολική Μακεδονία και Θράκη', 5),
       (6, 'Epirus / Ήπειρος', 5),
       (7, 'Ionian Islands / Ιόνια νησιά', 5),
       (8, 'North Aegean / Βόρειο Αιγαίο', 5),
       (9, 'Peloponnese / Πελοπόννησος', 5),
       (10, 'South Aegean / Νότιο Αιγαίο', 5),
       (11, 'Thessaly / Θεσσαλία', 5),
       (12, 'Western Greece / Δυτική Ελλάδα', 5),
       (13, 'Western Macedonia / Δυτική Μακεδονία', 5),
       (14, 'Mount Athos / Άγιον Όρος', 5);

WITH ranked_models AS (SELECT model_name,
                              version,
                              year_of_production,
                              drive,
                              fuel_type,
                              transmission,
                              car_type,
                              car_brand_id,
                              created_date,
                              update_date,
                              ROW_NUMBER() OVER (PARTITION BY model_name ORDER BY update_date DESC) AS model_row_num, ROW_NUMBER() OVER (PARTITION BY car_brand_id ORDER BY update_date DESC) AS brand_row_num
                       FROM car_model)
SELECT model_name,
       version,
       year_of_production,
       drive,
       fuel_type,
       transmission,
       car_type,
       car_brand_id,
       created_date,
       update_date
FROM ranked_models
WHERE model_row_num = 1
   OR brand_row_num <= 5
ORDER BY car_brand_id, model_name, brand_row_num;


-- Insert Data into Functions Table
INSERT INTO sub_part_category (sub_part_category_name, main_part_category_id)
VALUES
-- Exterior Parts
('Hood', 1),
('Trunk lid', 1),
('Roof', 1),
('Fenders', 1),
('Quarter panels', 1),
('Doors', 1),
('Windshield', 1),
('Side windows', 1),
('Rear window', 1),
('Side mirrors', 1),
('Rearview mirror', 1),
('Headlights', 1),
('Tail lights', 1),
('Fog lights', 1),
('Turn signals', 1),
('Brake lights', 1),
('License plate lights', 1),
('Rims', 1),
('Tires', 1),
('Lug nuts', 1),
('Hubcaps', 1),
('Front bumper', 1),
('Rear bumper', 1),
('Front grille', 1),
('Side moldings', 1),
('Roof rails', 1),
('Emblems', 1),
('Windshield wipers', 1),
('Wiper blades', 1),
('Antenna', 1),

-- Interior Parts
('Instrument cluster', 2),
('Center console', 2),
('Glove compartment', 2),
('Air vents', 2),
('Front seats', 2),
('Rear seats', 2),
('Headrests', 2),
('Seatbelts', 2),
('Steering wheel', 2),
('Steering column', 2),
('Horn', 2),
('Gear shifter', 2),
('Handbrake', 2),
('Accelerator pedal', 2),
('Brake pedal', 2),
('Clutch pedal', 2),
('Carpet', 2),
('Door panels', 2),
('Headliner', 2),
('Radio', 2),
('Speakers', 2),
('Infotainment system', 2),
('Navigation system', 2),
('Air conditioning vents', 2),
('Heating controls', 2),

-- Engine and Related Components
('Engine block', 3),
('Cylinder head', 3),
('Pistons', 3),
('Crankshaft', 3),
('Camshaft', 3),
('Timing belt/chain', 3),
('Spark plugs', 3),
('Fuel injectors', 3),
('Air intake manifold', 3),
('Exhaust manifold', 3),
('Oil filter', 3),
('Radiator', 3),
('Cooling fan', 3),
('Water pump', 3),
('Turbocharger/Supercharger', 3),

-- Transmission System
('Transmission', 4),
('Clutch', 4),
('Gearbox', 4),
('Driveshaft', 4),
('Axles', 4),

-- Suspension and Steering
('Shock absorbers', 5),
('Struts', 5),
('Springs', 5),
('Control arms', 5),
('Power steering pump', 5),
('Tie rods', 5),
('Steering knuckle', 5),
('Steering rack', 5),

-- Brake System
('Brake pads', 6),
('Brake rotors', 6),
('Brake calipers', 6),
('Brake lines', 6),
('Parking brake cables', 6),

-- Exhaust System
('Muffler', 7),
('Catalytic converter', 7),
('Exhaust pipe', 7),

-- Electrical System
('Battery', 8),
('Alternator', 8),
('Starter motor', 8),
('Fuse box', 8),
('Wiring harness', 8),

-- Fuel System
('Fuel tank', 9),
('Fuel pump', 9),
('Fuel filter', 9),

-- Miscellaneous
('Spare tire', 10),
('Jack', 10),
('Tools', 10),
('Engine oil', 10),
('Transmission fluid', 10),
('Brake fluid', 10),
('Coolant', 10),
('Washer fluid', 10),
('Oxygen sensor', 10),
('Mass airflow sensor', 10),
('Crankshaft position sensor', 10);


INSERT INTO car_brand (brand_name, country_of_origin, year_of_foundation)
VALUES ('Abarth', 'Italy', 1949),
       ('Acura', 'Japan', 1986),
       ('Alfa Romeo', 'Italy', 1910),
       ('Alpine', 'France', 1955),
       ('Aston Martin', 'UK', 1913),
       ('Audi', 'Germany', 1909),
       ('Austin', 'UK', 1905),
       ('Bentley', 'UK', 1919),
       ('BMW', 'Germany', 1916),
       ('Bugatti', 'France', 1909),
       ('Buick', 'USA', 1899),
       ('Cadillac', 'USA', 1902),
       ('Chevrolet', 'USA', 1911),
       ('Chrysler', 'USA', 1925),
       ('Citroen', 'France', 1919),
       ('Cupra', 'Spain', 2018),
       ('Dacia', 'Romania', 1966),
       ('Daihatsu', 'Japan', 1907),
       ('Dodge', 'USA', 1900),
       ('DS Automobiles', 'France', 2009),
       ('Ferrari', 'Italy', 1947),
       ('Fiat', 'Italy', 1899),
       ('Ford', 'USA', 1903),
       ('Genesis', 'South Korea', 2015),
       ('GMC', 'USA', 1912),
       ('Honda', 'Japan', 1948),
       ('Hummer', 'USA', 1992),
       ('Hyundai', 'South Korea', 1967),
       ('Infiniti', 'Japan', 1989),
       ('Isuzu', 'Japan', 1916),
       ('Jaguar', 'UK', 1922),
       ('Jeep', 'USA', 1941),
       ('Kia', 'South Korea', 1944),
       ('Koenigsegg', 'Sweden', 1994),
       ('Lamborghini', 'Italy', 1963),
       ('Lancia', 'Italy', 1906),
       ('Land Rover', 'UK', 1948),
       ('Lexus', 'Japan', 1989),
       ('Lincoln', 'USA', 1917),
       ('Lotus', 'UK', 1952),
       ('Maserati', 'Italy', 1914),
       ('Maybach', 'Germany', 1909),
       ('Mazda', 'Japan', 1920),
       ('McLaren', 'UK', 1963),
       ('Mercedes-Benz', 'Germany', 1926),
       ('MG', 'UK', 1924),
       ('Mini', 'UK', 1959),
       ('Mitsubishi', 'Japan', 1970),
       ('Nissan', 'Japan', 1933),
       ('Noble', 'UK', 1999),
       ('Opel', 'Germany', 1862),
       ('Pagani', 'Italy', 1992),
       ('Peugeot', 'France', 1810),
       ('Pininfarina', 'Italy', 1930),
       ('Polestar', 'Sweden', 2017),
       ('Porsche', 'Germany', 1931),
       ('Ram', 'USA', 2010),
       ('Renault', 'France', 1898),
       ('Rolls-Royce', 'UK', 1906),
       ('Saab', 'Sweden', 1945),
       ('Seat', 'Spain', 1950),
       ('Skoda', 'Czech Republic', 1895),
       ('Smart', 'Germany', 1994),
       ('SsangYong', 'South Korea', 1954),
       ('Subaru', 'Japan', 1953),
       ('Suzuki', 'Japan', 1909),
       ('Tesla', 'USA', 2003),
       ('Toyota', 'Japan', 1937),
       ('Vauxhall', 'UK', 1857),
       ('Volkswagen', 'Germany', 1937),
       ('Volvo', 'Sweden', 1927),
       ('Wuling', 'China', 1958),
       ('Zenvo', 'Denmark', 2004),
       ('Zotye', 'China', 2005),
       ('Saturn', 'USA', 1985),
       ('Mercury', 'USA', 1938),
       ('CX Automotive', 'Unknown', 1900),
       ('Oldsmobile', 'USA', 1897),
       ('Plymouth', 'USA', 1928),
       ('Pontiac', 'USA', 1926),
       ('Eagle', 'USA', 1987),
       ('AM General', 'USA', 1971);

INSERT INTO car_model (model_name, version, year_of_production, drive, fuel_type, transmission, car_type, car_brand_id, created_date, update_date)
VALUES
    ('Spider Veloce 2000', 1, 1985, 'Rear-Wheel Drive', 'Regular', 'Manual 5-spd', 'Two Seaters', 3, NOW(), NOW()),
    ('Testarossa', 1, 1985, 'Rear-Wheel Drive', 'Regular', 'Manual 5-spd', 'Two Seaters', 21, NOW(), NOW()),
    ('Charger', 1, 1985, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Subcompact Cars', 19, NOW(), NOW()),
    ('B150/B250 Wagon 2WD', 1, 1985, 'Rear-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Vans', 19, NOW(), NOW()),
    ('Legacy AWD Turbo', 1, 1993, '4-Wheel or All-Wheel Drive', 'Premium', 'Manual 5-spd', 'Compact Cars', 65, NOW(), NOW()),
    ('Loyale', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Compact Cars', 65, NOW(), NOW()),
    ('Loyale', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Compact Cars', 65, NOW(), NOW()),
    ('Corolla', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Compact Cars', 68, NOW(), NOW()),
    ('Corolla', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Compact Cars', 68, NOW(), NOW()),
    ('Corolla', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Compact Cars', 68, NOW(), NOW()),
    ('Golf III / GTI', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Compact Cars', 70, NOW(), NOW()),
    ('Golf III / GTI', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Compact Cars', 70, NOW(), NOW()),
    ('Jetta III', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Compact Cars', 70, NOW(), NOW()),
    ('Jetta III', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Compact Cars', 70, NOW(), NOW()),
    ('240', 1, 1993, 'Rear-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Compact Cars', 71, NOW(), NOW()),
    ('240', 1, 1993, 'Rear-Wheel Drive', 'Regular', 'Manual 5-spd', 'Compact Cars', 71, NOW(), NOW()),
    ('100', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Automatic 4-spd', 'Midsize Cars', 6, NOW(), NOW()),
    ('100', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Manual 5-spd', 'Midsize Cars', 6, NOW(), NOW()),
    ('740i', 1, 1993, 'Rear-Wheel Drive', 'Premium', 'Automatic 5-spd', 'Midsize Cars', 9, NOW(), NOW()),
    ('740il', 1, 1993, 'Rear-Wheel Drive', 'Premium', 'Automatic 5-spd', 'Midsize Cars', 9, NOW(), NOW()),
    ('750il', 1, 1993, 'Rear-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 9, NOW(), NOW()),
    ('Century', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Midsize Cars', 11, NOW(), NOW()),
    ('Century', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 11, NOW(), NOW()),
    ('Regal', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Midsize Cars', 11, NOW(), NOW()),
    ('Regal', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 11, NOW(), NOW()),
    ('Riviera', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 11, NOW(), NOW()),
    ('Eldorado', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Automatic 4-spd', 'Midsize Cars', 12, NOW(), NOW()),
    ('Seville', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Automatic 4-spd', 'Midsize Cars', 12, NOW(), NOW()),
    ('Lumina', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Midsize Cars', 13, NOW(), NOW()),
    ('Lumina', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 13, NOW(), NOW()),
    ('Lumina', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Midsize Cars', 13, NOW(), NOW()),
    ('New Yorker', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 14, NOW(), NOW()),
    ('XM v6', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Manual 5-spd', 'Midsize Cars', 78, NOW(), NOW()),
    ('XM v6a', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Automatic 4-spd', 'Midsize Cars', 78, NOW(), NOW()),
    ('Maxima', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Automatic 4-spd', 'Midsize Cars', 49, NOW(), NOW()),
    ('Maxima', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Manual 5-spd', 'Midsize Cars', 49, NOW(), NOW()),
    ('Dynasty', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Midsize Cars', 19, NOW(), NOW()),
    ('Dynasty', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 19, NOW(), NOW()),
    ('Spirit', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 3-spd', 'Midsize Cars', 19, NOW(), NOW()),
    ('Spirit', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Manual 5-spd', 'Midsize Cars', 19, NOW(), NOW()),
    ('Spirit', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 19, NOW(), NOW()),
    ('Taurus', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 23, NOW(), NOW()),
    ('Taurus SHO', 1, 1993, 'Front-Wheel Drive', 'Premium', 'Manual 5-spd', 'Midsize Cars', 23, NOW(), NOW()),
    ('Thunderbird', 1, 1993, 'Rear-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 23, NOW(), NOW()),
    ('Thunderbird', 1, 1993, 'Rear-Wheel Drive', 'Premium', 'Automatic 4-spd', 'Midsize Cars', 23, NOW(), NOW()),
    ('Thunderbird', 1, 1993, 'Rear-Wheel Drive', 'Premium', 'Manual 5-spd', 'Midsize Cars', 23, NOW(), NOW()),
    ('Sonata', 1, 1993, 'Front-Wheel Drive', 'Regular', 'Automatic 4-spd', 'Midsize Cars', 28, NOW(), NOW());