DROP DATABASE IF EXISTS warehouseManagerDB;

DROP USER IF EXISTS `warehouseManager`@`%`;


CREATE DATABASE IF NOT EXISTS warehouseManagerDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `warehouseManager`@`%` IDENTIFIED WITH mysql_native_password BY 'warehouseManager';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `warehouseManagerDB`.* TO `warehouseManager`@`%`;

