


-- Insert Data into Functions Table
INSERT INTO Sub_Part_Category (sub_part_category_name, main_part_category_id) VALUES
-- Exterior Parts
('Hood', 1),
('Trunk lid', 1),
('Roof', 1),
('Fenders', 1),
('Quarter panels', 1),
('Doors', 1),
('Windshield', 1),
('Side windows', 1),
('Rear window', 1),
('Side mirrors', 1),
('Rearview mirror', 1),
('Headlights', 1),
('Tail lights', 1),
('Fog lights', 1),
('Turn signals', 1),
('Brake lights', 1),
('License plate lights', 1),
('Rims', 1),
('Tires', 1),
('Lug nuts', 1),
('Hubcaps', 1),
('Front bumper', 1),
('Rear bumper', 1),
('Front grille', 1),
('Side moldings', 1),
('Roof rails', 1),
('Emblems', 1),
('Windshield wipers', 1),
('Wiper blades', 1),
('Antenna', 1),

-- Interior Parts
('Instrument cluster', 2),
('Center console', 2),
('Glove compartment', 2),
('Air vents', 2),
('Front seats', 2),
('Rear seats', 2),
('Headrests', 2),
('Seatbelts', 2),
('Steering wheel', 2),
('Steering column', 2),
('Horn', 2),
('Gear shifter', 2),
('Handbrake', 2),
('Accelerator pedal', 2),
('Brake pedal', 2),
('Clutch pedal', 2),
('Carpet', 2),
('Door panels', 2),
('Headliner', 2),
('Radio', 2),
('Speakers', 2),
('Infotainment system', 2),
('Navigation system', 2),
('Air conditioning vents', 2),
('Heating controls', 2),

-- Engine and Related Components
('Engine block', 3),
('Cylinder head', 3),
('Pistons', 3),
('Crankshaft', 3),
('Camshaft', 3),
('Timing belt/chain', 3),
('Spark plugs', 3),
('Fuel injectors', 3),
('Air intake manifold', 3),
('Exhaust manifold', 3),
('Oil filter', 3),
('Radiator', 3),
('Cooling fan', 3),
('Water pump', 3),
('Turbocharger/Supercharger', 3),

-- Transmission System
('Transmission', 4),
('Clutch', 4),
('Gearbox', 4),
('Driveshaft', 4),
('Axles', 4),

-- Suspension and Steering
('Shock absorbers', 5),
('Struts', 5),
('Springs', 5),
('Control arms', 5),
('Power steering pump', 5),
('Tie rods', 5),
('Steering knuckle', 5),
('Steering rack', 5),

-- Brake System
('Brake pads', 6),
('Brake rotors', 6),
('Brake calipers', 6),
('Brake lines', 6),
('Parking brake cables', 6),

-- Exhaust System
('Muffler', 7),
('Catalytic converter', 7),
('Exhaust pipe', 7),

-- Electrical System
('Battery', 8),
('Alternator', 8),
('Starter motor', 8),
('Fuse box', 8),
('Wiring harness', 8),

-- Fuel System
('Fuel tank', 9),
('Fuel pump', 9),
('Fuel filter', 9),

-- Miscellaneous
('Spare tire', 10),
('Jack', 10),
('Tools', 10),
('Engine oil', 10),
('Transmission fluid', 10),
('Brake fluid', 10),
('Coolant', 10),
('Washer fluid', 10),
('Oxygen sensor', 10),
('Mass airflow sensor', 10),
('Crankshaft position sensor', 10);
